export interface Bank {
  name: string;
  code: string;
  routingNumber?: string;
}

/** Static bank list per ISO 3166-1 alpha-2 country code */
export const BANKS_BY_COUNTRY: Record<string, Bank[]> = {
  NG: [
    { name: "Access Bank", code: "044", routingNumber: "044150149" },
    { name: "Citibank", code: "023", routingNumber: "023150005" },
    { name: "Ecobank", code: "050", routingNumber: "050150010" },
    { name: "Fidelity Bank", code: "070", routingNumber: "070150003" },
    { name: "First Bank of Nigeria", code: "011", routingNumber: "011151003" },
    { name: "First City Monument Bank (FCMB)", code: "214", routingNumber: "214150018" },
    { name: "Globus Bank", code: "00103", routingNumber: "103150006" },
    { name: "Guaranty Trust Bank (GTBank)", code: "058", routingNumber: "058152036" },
    { name: "Heritage Bank", code: "030", routingNumber: "030159992" },
    { name: "Keystone Bank", code: "082", routingNumber: "082150017" },
    { name: "Kuda Bank", code: "50211", routingNumber: "090267" },
    { name: "Opay", code: "999992", routingNumber: "100004" },
    { name: "Palmpay", code: "999991", routingNumber: "100033" },
    { name: "Polaris Bank", code: "076", routingNumber: "076151006" },
    { name: "Providus Bank", code: "101", routingNumber: "101150008" },
    { name: "Stanbic IBTC Bank", code: "221", routingNumber: "221159522" },
    { name: "Standard Chartered Bank", code: "068", routingNumber: "068150015" },
    { name: "Sterling Bank", code: "232", routingNumber: "232150016" },
    { name: "SunTrust Bank", code: "100", routingNumber: "100150010" },
    { name: "Union Bank", code: "032", routingNumber: "032080474" },
    { name: "United Bank for Africa (UBA)", code: "033", routingNumber: "033153513" },
    { name: "Unity Bank", code: "215", routingNumber: "215154097" },
    { name: "VFD Microfinance Bank", code: "566", routingNumber: "090110" },
    { name: "Wema Bank", code: "035", routingNumber: "035150103" },
    { name: "Zenith Bank", code: "057", routingNumber: "057150013" },
  ],
  GH: [
    { name: "Absa Bank Ghana", code: "ABSA" },
    { name: "Access Bank Ghana", code: "ACCESS" },
    { name: "Agricultural Development Bank (ADB)", code: "ADB" },
    { name: "Bank of Ghana", code: "BOG" },
    { name: "Consolidated Bank Ghana", code: "CBG" },
    { name: "Ecobank Ghana", code: "ECO" },
    { name: "Fidelity Bank Ghana", code: "FID" },
    { name: "First Atlantic Bank", code: "FAB" },
    { name: "First National Bank Ghana", code: "FNB" },
    { name: "GCB Bank", code: "GCB" },
    { name: "Guaranty Trust Bank Ghana", code: "GTB" },
    { name: "National Investment Bank", code: "NIB" },
    { name: "OmniBSIC Bank", code: "OMNI" },
    { name: "Prudential Bank", code: "PRU" },
    { name: "Republic Bank Ghana", code: "REP" },
    { name: "Stanbic Bank Ghana", code: "STB" },
    { name: "Standard Chartered Ghana", code: "SCB" },
    { name: "United Bank for Africa Ghana", code: "UBA" },
    { name: "Universal Merchant Bank", code: "UMB" },
    { name: "Zenith Bank Ghana", code: "ZBG" },
  ],
  KE: [
    { name: "Absa Bank Kenya", code: "ABSA" },
    { name: "Bank of Africa Kenya", code: "BOA" },
    { name: "Bank of Baroda Kenya", code: "BOB" },
    { name: "Citibank Kenya", code: "CITI" },
    { name: "Co-operative Bank", code: "COOP" },
    { name: "DTB Bank", code: "DTB" },
    { name: "Ecobank Kenya", code: "ECO" },
    { name: "Equity Bank", code: "EQB" },
    { name: "Family Bank", code: "FAM" },
    { name: "Gulf African Bank", code: "GAB" },
    { name: "I&M Bank", code: "IM" },
    { name: "KCB Bank", code: "KCB" },
    { name: "M-Pesa (Safaricom)", code: "MPESA" },
    { name: "Mpesa Business", code: "MPESAB" },
    { name: "NCBA Bank", code: "NCBA" },
    { name: "Prime Bank Kenya", code: "PBK" },
    { name: "Sidian Bank", code: "SID" },
    { name: "Stanbic Bank Kenya", code: "STB" },
    { name: "Standard Chartered Kenya", code: "SCB" },
    { name: "United Bank for Africa Kenya", code: "UBA" },
  ],
  ZA: [
    { name: "Absa Bank", code: "ABSA", routingNumber: "632005" },
    { name: "African Bank", code: "AFRI", routingNumber: "430000" },
    { name: "Bidvest Bank", code: "BIDV", routingNumber: "462005" },
    { name: "Capitec Bank", code: "CAP", routingNumber: "470010" },
    { name: "Discovery Bank", code: "DIS", routingNumber: "679000" },
    { name: "FNB (First National Bank)", code: "FNB", routingNumber: "250655" },
    { name: "Grindrod Bank", code: "GRI", routingNumber: "584000" },
    { name: "Investec Bank", code: "INV", routingNumber: "580105" },
    { name: "Mercantile Bank", code: "MER", routingNumber: "450905" },
    { name: "Nedbank", code: "NED", routingNumber: "198765" },
    { name: "Old Mutual Bank", code: "OMB", routingNumber: "642005" },
    { name: "Sasfin Bank", code: "SAS", routingNumber: "683000" },
    { name: "Standard Bank", code: "STD", routingNumber: "051001" },
    { name: "TymeBank", code: "TYM", routingNumber: "678910" },
    { name: "Ubank", code: "UBK", routingNumber: "431010" },
  ],
  US: [
    { name: "Bank of America", code: "BOA", routingNumber: "026009593" },
    { name: "BB&T (Truist)", code: "BBT", routingNumber: "053101121" },
    { name: "Capital One", code: "CAP1", routingNumber: "051405515" },
    { name: "Charles Schwab Bank", code: "SCHWAB", routingNumber: "121202211" },
    { name: "Chase (JPMorgan Chase)", code: "CHASE", routingNumber: "021000021" },
    { name: "Citibank", code: "CITI", routingNumber: "021000089" },
    { name: "Citizens Bank", code: "CIT", routingNumber: "011500120" },
    { name: "Discover Bank", code: "DIS", routingNumber: "031100649" },
    { name: "Fifth Third Bank", code: "FIFTH", routingNumber: "042000314" },
    { name: "Goldman Sachs (Marcus)", code: "GS", routingNumber: "124085066" },
    { name: "HSBC USA", code: "HSBC", routingNumber: "022000020" },
    { name: "KeyBank", code: "KEY", routingNumber: "041001039" },
    { name: "M&T Bank", code: "MT", routingNumber: "022000046" },
    { name: "Navy Federal Credit Union", code: "NAVY", routingNumber: "256074974" },
    { name: "PNC Bank", code: "PNC", routingNumber: "043000096" },
    { name: "Regions Bank", code: "REG", routingNumber: "062000019" },
    { name: "SunTrust (Truist)", code: "SUN", routingNumber: "061000104" },
    { name: "TD Bank", code: "TDB", routingNumber: "031101266" },
    { name: "US Bank", code: "USB", routingNumber: "091000022" },
    { name: "Wells Fargo", code: "WF", routingNumber: "121042882" },
  ],
  GB: [
    { name: "Barclays", code: "BARC", routingNumber: "20-00-00" },
    { name: "Clydesdale Bank", code: "CLY", routingNumber: "82-61-00" },
    { name: "Co-operative Bank", code: "COOP", routingNumber: "08-93-00" },
    { name: "HSBC UK", code: "HSBC", routingNumber: "40-47-84" },
    { name: "Lloyds Bank", code: "LLOY", routingNumber: "30-00-00" },
    { name: "Metro Bank", code: "METR", routingNumber: "23-05-80" },
    { name: "Monzo", code: "MONZO", routingNumber: "04-00-03" },
    { name: "Nationwide Building Society", code: "NATI", routingNumber: "07-00-93" },
    { name: "NatWest", code: "NATW", routingNumber: "60-00-01" },
    { name: "Revolut", code: "REVO", routingNumber: "04-29-09" },
    { name: "Royal Bank of Scotland", code: "RBS", routingNumber: "16-00-15" },
    { name: "Santander UK", code: "SANT", routingNumber: "09-01-27" },
    { name: "Standard Chartered UK", code: "SCB", routingNumber: "60-95-19" },
    { name: "Starling Bank", code: "STAR", routingNumber: "60-83-71" },
    { name: "TSB Bank", code: "TSB", routingNumber: "30-91-82" },
    { name: "Virgin Money", code: "VIRG", routingNumber: "82-22-00" },
    { name: "Yorkshire Bank", code: "YORK", routingNumber: "05-07-08" },
  ],
  CA: [
    { name: "ATB Financial", code: "ATB", routingNumber: "219" },
    { name: "Bank of Montreal (BMO)", code: "BMO", routingNumber: "001" },
    { name: "Bank of Nova Scotia (Scotiabank)", code: "BNS", routingNumber: "002" },
    { name: "Canadian Imperial Bank (CIBC)", code: "CIBC", routingNumber: "010" },
    { name: "Canadian Western Bank", code: "CWB", routingNumber: "030" },
    { name: "Desjardins", code: "DES", routingNumber: "815" },
    { name: "EQ Bank", code: "EQ", routingNumber: "623" },
    { name: "HSBC Canada", code: "HSBC", routingNumber: "016" },
    { name: "Laurentian Bank", code: "LB", routingNumber: "039" },
    { name: "Manulife Bank", code: "MAN", routingNumber: "540" },
    { name: "National Bank of Canada", code: "NBC", routingNumber: "006" },
    { name: "Royal Bank of Canada (RBC)", code: "RBC", routingNumber: "003" },
    { name: "Simplii Financial", code: "SIM", routingNumber: "010" },
    { name: "Tangerine Bank", code: "TAN", routingNumber: "614" },
    { name: "TD Canada Trust", code: "TD", routingNumber: "004" },
  ],
  AU: [
    { name: "ANZ Bank", code: "ANZ", routingNumber: "013" },
    { name: "Bank of Queensland", code: "BOQ", routingNumber: "124" },
    { name: "Bendigo Bank", code: "BEN", routingNumber: "633" },
    { name: "Commonwealth Bank (CBA)", code: "CBA", routingNumber: "062" },
    { name: "Citibank Australia", code: "CITI", routingNumber: "242" },
    { name: "HSBC Australia", code: "HSBC", routingNumber: "342" },
    { name: "ING Australia", code: "ING", routingNumber: "923" },
    { name: "Macquarie Bank", code: "MQG", routingNumber: "182" },
    { name: "ME Bank", code: "ME", routingNumber: "302" },
    { name: "NAB (National Australia Bank)", code: "NAB", routingNumber: "083" },
    { name: "St George Bank", code: "STG", routingNumber: "112" },
    { name: "Suncorp Bank", code: "SUN", routingNumber: "484" },
    { name: "Westpac", code: "WBC", routingNumber: "032" },
  ],
  IN: [
    { name: "Axis Bank", code: "AXIS", routingNumber: "UTIB" },
    { name: "Bank of Baroda", code: "BOB", routingNumber: "BARB" },
    { name: "Bank of India", code: "BOI", routingNumber: "BKID" },
    { name: "Canara Bank", code: "CAN", routingNumber: "CNRB" },
    { name: "Central Bank of India", code: "CBI", routingNumber: "CBIN" },
    { name: "City Union Bank", code: "CUB", routingNumber: "CIUB" },
    { name: "DBS Bank India", code: "DBS", routingNumber: "DBSS" },
    { name: "Federal Bank", code: "FED", routingNumber: "FDRL" },
    { name: "HDFC Bank", code: "HDFC", routingNumber: "HDFC" },
    { name: "ICICI Bank", code: "ICICI", routingNumber: "ICIC" },
    { name: "IDFC FIRST Bank", code: "IDFC", routingNumber: "IDFB" },
    { name: "Indian Bank", code: "IND", routingNumber: "IDIB" },
    { name: "IndusInd Bank", code: "INDUS", routingNumber: "INDB" },
    { name: "Kotak Mahindra Bank", code: "KOTAK", routingNumber: "KKBK" },
    { name: "Punjab National Bank (PNB)", code: "PNB", routingNumber: "PUNB" },
    { name: "RBL Bank", code: "RBL", routingNumber: "RATN" },
    { name: "State Bank of India (SBI)", code: "SBI", routingNumber: "SBIN" },
    { name: "UCO Bank", code: "UCO", routingNumber: "UCBA" },
    { name: "Union Bank of India", code: "UNION", routingNumber: "UBIN" },
    { name: "Yes Bank", code: "YES", routingNumber: "YESB" },
  ],
  DE: [
    { name: "Commerzbank", code: "COMM", routingNumber: "20040000" },
    { name: "Deutsche Bank", code: "DEUT", routingNumber: "10070000" },
    { name: "DZ Bank", code: "DZBK", routingNumber: "50060400" },
    { name: "ING-DiBa", code: "INGD", routingNumber: "50010517" },
    { name: "KfW Bank", code: "KFWB", routingNumber: "50020400" },
    { name: "Landesbank Baden-Württemberg (LBBW)", code: "LBBW", routingNumber: "60050101" },
    { name: "N26", code: "N26", routingNumber: "10011001" },
    { name: "Postbank", code: "POST", routingNumber: "20010020" },
    { name: "Sparkasse", code: "SPAR", routingNumber: "10050000" },
    { name: "UniCredit Bank (HypoVereinsbank)", code: "HYPO", routingNumber: "70020270" },
    { name: "Volksbank Raiffeisenbank", code: "VOLK", routingNumber: "30060601" },
  ],
  FR: [
    { name: "BNP Paribas", code: "BNPP" },
    { name: "Boursorama Banque", code: "BOUR" },
    { name: "Caisse d'Épargne", code: "CEPA" },
    { name: "Crédit Agricole", code: "AGRI" },
    { name: "Crédit Mutuel", code: "CRMU" },
    { name: "Hello bank!", code: "HELL" },
    { name: "HSBC France", code: "HSBC" },
    { name: "La Banque Postale", code: "POST" },
    { name: "LCL", code: "LCL" },
    { name: "Monabanq", code: "MONA" },
    { name: "Nickel", code: "NICK" },
    { name: "Orange Bank", code: "ORAN" },
    { name: "Société Générale", code: "SOGE" },
  ],
  AE: [
    { name: "Abu Dhabi Commercial Bank (ADCB)", code: "ADCB" },
    { name: "Abu Dhabi Islamic Bank (ADIB)", code: "ADIB" },
    { name: "Al Hilal Bank", code: "ALHB" },
    { name: "Arab Bank UAE", code: "ARAB" },
    { name: "Bank of Sharjah", code: "BSHA" },
    { name: "Commercial Bank of Dubai (CBD)", code: "CBD" },
    { name: "Citibank UAE", code: "CITI" },
    { name: "Dubai Islamic Bank (DIB)", code: "DIB" },
    { name: "Emirates Islamic Bank", code: "EIB" },
    { name: "Emirates NBD", code: "ENBD" },
    { name: "First Abu Dhabi Bank (FAB)", code: "FAB" },
    { name: "HSBC UAE", code: "HSBC" },
    { name: "Mashreq Bank", code: "MASH" },
    { name: "Noor Bank", code: "NOOR" },
    { name: "RAK Bank", code: "RAKB" },
    { name: "Sharjah Islamic Bank (SIB)", code: "SIB" },
    { name: "Standard Chartered UAE", code: "SCB" },
    { name: "United Arab Bank (UAB)", code: "UAB" },
  ],
  SG: [
    { name: "Bank of China Singapore", code: "BOCS" },
    { name: "Citibank Singapore", code: "CITI" },
    { name: "DBS Bank", code: "DBS", routingNumber: "7171" },
    { name: "HSBC Singapore", code: "HSBC" },
    { name: "Maybank Singapore", code: "MAYB", routingNumber: "7302" },
    { name: "OCBC Bank", code: "OCBC", routingNumber: "7339" },
    { name: "Standard Chartered Singapore", code: "SCB" },
    { name: "UOB (United Overseas Bank)", code: "UOB", routingNumber: "7375" },
  ],
  ZW: [
    { name: "CBZ Bank", code: "CBZ" },
    { name: "EcoBank Zimbabwe", code: "ECO" },
    { name: "FBC Bank", code: "FBC" },
    { name: "First Capital Bank", code: "FCB" },
    { name: "Metbank", code: "MET" },
    { name: "NMB Bank", code: "NMB" },
    { name: "Steward Bank", code: "STB" },
    { name: "ZB Bank", code: "ZBB" },
  ],
  ZM: [
    { name: "Absa Bank Zambia", code: "ABSA" },
    { name: "Atlas Mara Bank", code: "ATLAS" },
    { name: "Bank of China Zambia", code: "BOC" },
    { name: "Citibank Zambia", code: "CITI" },
    { name: "First Alliance Bank", code: "FAB" },
    { name: "First Capital Bank Zambia", code: "FCB" },
    { name: "First National Bank Zambia", code: "FNB" },
    { name: "Indo Zambia Bank", code: "IZB" },
    { name: "Investrust Bank", code: "INV" },
    { name: "Stanbic Bank Zambia", code: "STB" },
    { name: "Standard Chartered Zambia", code: "SCB" },
    { name: "United Bank for Africa Zambia", code: "UBA" },
    { name: "Zanaco", code: "ZAN" },
  ],

  // Africa (continued)
  TZ: [
    { name: "CRDB Bank", code: "CRDB" },
    { name: "NMB Bank Tanzania", code: "NMB" },
    { name: "NBC Tanzania", code: "NBC" },
    { name: "Stanbic Tanzania", code: "STB" },
    { name: "Equity Bank Tanzania", code: "EQB" },
  ],
  UG: [
    { name: "Centenary Bank", code: "CEN" },
    { name: "Equity Bank Uganda", code: "EQB" },
    { name: "KCB Uganda", code: "KCB" },
    { name: "Stanbic Uganda", code: "STB" },
    { name: "Standard Chartered Uganda", code: "SCB" },
  ],
  RW: [
    { name: "Bank of Kigali", code: "BOK" },
    { name: "Equity Bank Rwanda", code: "EQB" },
    { name: "I&M Bank Rwanda", code: "IMB" },
    { name: "KCB Rwanda", code: "KCB" },
  ],
  ET: [
    { name: "Awash Bank", code: "AWB" },
    { name: "Commercial Bank of Ethiopia", code: "CBE" },
    { name: "Dashen Bank", code: "DSH" },
    { name: "Enat Bank", code: "ENT" },
  ],
  SN: [
    { name: "Banque de l'Habitat du Sénégal", code: "BHS" },
    { name: "Ecobank Senegal", code: "ECO" },
    { name: "Société Générale Sénégal", code: "SGS" },
    { name: "UBA Senegal", code: "UBA" },
  ],
  CI: [
    { name: "Ecobank Côte d'Ivoire", code: "ECO" },
    { name: "SGBCI", code: "SGB" },
    { name: "NSIA Banque", code: "NSI" },
    { name: "UBA Côte d'Ivoire", code: "UBA" },
  ],
  CM: [
    { name: "Afriland First Bank", code: "AFR" },
    { name: "Ecobank Cameroon", code: "ECO" },
    { name: "SCB Cameroon", code: "SCB" },
    { name: "UBA Cameroon", code: "UBA" },
  ],
  EG: [
    { name: "Banque Misr", code: "BMR" },
    { name: "CIB Egypt", code: "CIB" },
    { name: "National Bank of Egypt", code: "NBE" },
    { name: "QNB Egypt", code: "QNB" },
    { name: "Arab African International Bank", code: "AAIB" },
  ],
  MA: [
    { name: "Attijariwafa Bank", code: "ATT" },
    { name: "Banque Populaire", code: "BPM" },
    { name: "BMCE Bank", code: "BMC" },
    { name: "CIH Bank", code: "CIH" },
    { name: "Société Générale Maroc", code: "SGM" },
  ],
  MZ: [
    { name: "BCI Mozambique", code: "BCI" },
    { name: "Millennium BIM", code: "MBM" },
    { name: "Standard Bank Mozambique", code: "SBM" },
  ],
  MW: [
    { name: "FDH Bank", code: "FDH" },
    { name: "National Bank of Malawi", code: "NBM" },
    { name: "Standard Bank Malawi", code: "SBM" },
  ],
  AO: [
    { name: "Banco de Fomento Angola", code: "BFA" },
    { name: "Banco BIC", code: "BIC" },
    { name: "Banco Sol", code: "SOL" },
    { name: "Standard Bank Angola", code: "SBA" },
  ],
  // Middle East
  SA: [
    { name: "Al Rajhi Bank", code: "RAJH" },
    { name: "Arab National Bank", code: "ANB" },
    { name: "Alinma Bank", code: "ALIN" },
    { name: "Banque Saudi Fransi", code: "BSF" },
    { name: "Riyad Bank", code: "RIYA" },
    { name: "Saudi National Bank (SNB)", code: "SNB" },
  ],
  QA: [
    { name: "Commercial Bank of Qatar", code: "CBQ" },
    { name: "Doha Bank", code: "DOH" },
    { name: "Qatar Islamic Bank", code: "QIB" },
    { name: "Qatar National Bank", code: "QNB" },
  ],
  KW: [
    { name: "Burgan Bank", code: "BUR" },
    { name: "Gulf Bank", code: "GUL" },
    { name: "Kuwait Finance House", code: "KFH" },
    { name: "National Bank of Kuwait", code: "NBK" },
  ],
  IL: [
    { name: "Bank Hapoalim", code: "HAP" },
    { name: "Bank Leumi", code: "LEU" },
    { name: "Discount Bank", code: "DIS" },
    { name: "Mizrahi Tefahot Bank", code: "MIZ" },
  ],
  TR: [
    { name: "Akbank", code: "AKB" },
    { name: "Garanti BBVA", code: "GAR" },
    { name: "İş Bankası", code: "ISB" },
    { name: "Yapı Kredi", code: "YKB" },
    { name: "Ziraat Bankası", code: "ZIR" },
  ],
  // Asia
  JP: [
    { name: "Japan Post Bank", code: "JPB", routingNumber: "9900" },
    { name: "MUFG Bank", code: "MUFG", routingNumber: "0005" },
    { name: "Mizuho Bank", code: "MIZ", routingNumber: "0001" },
    { name: "Resona Bank", code: "RES", routingNumber: "0010" },
    { name: "Sumitomo Mitsui Banking", code: "SMBC", routingNumber: "0009" },
  ],
  CN: [
    { name: "Agricultural Bank of China", code: "ABC" },
    { name: "Bank of China", code: "BOC" },
    { name: "China Construction Bank", code: "CCB" },
    { name: "China Merchants Bank", code: "CMB" },
    { name: "Industrial and Commercial Bank", code: "ICBC" },
  ],
  KR: [
    { name: "IBK Bank", code: "IBK" },
    { name: "KB Kookmin Bank", code: "KBK" },
    { name: "KEB Hana Bank", code: "KEB" },
    { name: "Shinhan Bank", code: "SHN" },
    { name: "Woori Bank", code: "WOO" },
  ],
  PK: [
    { name: "Allied Bank", code: "ABL" },
    { name: "Habib Bank (HBL)", code: "HBL" },
    { name: "MCB Bank", code: "MCB" },
    { name: "Meezan Bank", code: "MEZ" },
    { name: "United Bank (UBL)", code: "UBL" },
  ],
  BD: [
    { name: "BRAC Bank", code: "BRAC" },
    { name: "Dutch-Bangla Bank", code: "DBB" },
    { name: "Islami Bank Bangladesh", code: "IBB" },
    { name: "Sonali Bank", code: "SON" },
  ],
  MY: [
    { name: "CIMB Bank", code: "CIMB", routingNumber: "0060" },
    { name: "Hong Leong Bank", code: "HLB", routingNumber: "0012" },
    { name: "Maybank", code: "MBB", routingNumber: "0001" },
    { name: "Public Bank Berhad", code: "PBB", routingNumber: "0009" },
    { name: "RHB Bank", code: "RHB", routingNumber: "0053" },
  ],
  TH: [
    { name: "Bangkok Bank", code: "BBL", routingNumber: "002" },
    { name: "Kasikorn Bank (KBank)", code: "KBANK", routingNumber: "004" },
    { name: "Krung Thai Bank", code: "KTB", routingNumber: "006" },
    { name: "SCB (Siam Commercial)", code: "SCB", routingNumber: "014" },
    { name: "TMB Thanachart Bank", code: "TTB", routingNumber: "011" },
  ],
  PH: [
    { name: "BDO Unibank", code: "BDO" },
    { name: "BPI (Bank of the Philippine Islands)", code: "BPI" },
    { name: "Metrobank", code: "MET" },
    { name: "PNB Philippines", code: "PNB" },
    { name: "UnionBank Philippines", code: "UBP" },
  ],
  ID: [
    { name: "Bank BCA", code: "BCA" },
    { name: "Bank BNI", code: "BNI" },
    { name: "Bank BRI", code: "BRI" },
    { name: "Bank Mandiri", code: "BMD" },
    { name: "Bank CIMB Niaga", code: "CIMB" },
  ],
  VN: [
    { name: "Agribank", code: "AGR" },
    { name: "BIDV", code: "BIDV" },
    { name: "MB Bank", code: "MBB" },
    { name: "Techcombank", code: "TCB" },
    { name: "Vietcombank", code: "VCB" },
  ],
  // Europe extras
  ES: [
    { name: "Banco Sabadell", code: "SAB" },
    { name: "Bankinter", code: "BKT" },
    { name: "CaixaBank", code: "CAI" },
    { name: "BBVA Spain", code: "BBVA" },
    { name: "Santander Spain", code: "SAN" },
  ],
  IT: [
    { name: "Banca Intesa", code: "INT" },
    { name: "BNL", code: "BNL" },
    { name: "Mediobanca", code: "MED" },
    { name: "Unicredit Italy", code: "UCR" },
  ],
  NL: [
    { name: "ABN AMRO", code: "ABN" },
    { name: "ING Netherlands", code: "ING" },
    { name: "Rabobank", code: "RAB" },
    { name: "Triodos Bank", code: "TRI" },
  ],
  SE: [
    { name: "Handelsbanken", code: "HAN" },
    { name: "Nordea Sweden", code: "NOR" },
    { name: "SEB", code: "SEB" },
    { name: "Swedbank", code: "SWE" },
  ],
  NO: [
    { name: "DNB", code: "DNB" },
    { name: "Nordea Norway", code: "NOR" },
    { name: "SpareBank 1", code: "SPB" },
  ],
  CH: [
    { name: "Credit Suisse", code: "CS" },
    { name: "PostFinance", code: "PF" },
    { name: "Raiffeisen Switzerland", code: "RAI" },
    { name: "UBS", code: "UBS" },
    { name: "Zürcher Kantonalbank", code: "ZKB" },
  ],
  PL: [
    { name: "Alior Bank", code: "ALI" },
    { name: "Bank Pekao", code: "PEK" },
    { name: "mBank", code: "MBK" },
    { name: "PKO Bank Polski", code: "PKO" },
    { name: "Santander Poland", code: "SAN" },
  ],
  RU: [
    { name: "Alfa-Bank", code: "ALF" },
    { name: "Gazprombank", code: "GPB" },
    { name: "Sberbank", code: "SBR" },
    { name: "Tinkoff Bank", code: "TIN" },
    { name: "VTB Bank", code: "VTB" },
  ],
  UA: [
    { name: "Monobank", code: "MONO" },
    { name: "PrivatBank", code: "PRV" },
    { name: "Raiffeisen Bank Ukraine", code: "RAI" },
    { name: "Ukrgasbank", code: "UGB" },
  ],
  // Latin America
  BR: [
    { name: "Banco Bradesco", code: "BRD" },
    { name: "Banco do Brasil", code: "BB" },
    { name: "Banco Inter", code: "INT" },
    { name: "Caixa Econômica Federal", code: "CEF" },
    { name: "Itaú Unibanco", code: "ITU" },
    { name: "Nubank", code: "NUB" },
    { name: "Santander Brasil", code: "SAN" },
  ],
  MX: [
    { name: "BBVA Mexico", code: "BBVA" },
    { name: "Banorte", code: "BNO" },
    { name: "Citibanamex", code: "CIT" },
    { name: "HSBC Mexico", code: "HSBC" },
    { name: "Santander Mexico", code: "SAN" },
    { name: "Scotiabank Mexico", code: "SCO" },
  ],
  AR: [
    { name: "Banco de la Nación Argentina", code: "BNA" },
    { name: "Banco Galicia", code: "GAL" },
    { name: "BBVA Argentina", code: "BBVA" },
    { name: "Santander Argentina", code: "SAN" },
  ],
  CO: [
    { name: "Bancolombia", code: "BCO" },
    { name: "Banco de Bogotá", code: "BOG" },
    { name: "Davivienda", code: "DAV" },
    { name: "BBVA Colombia", code: "BBVA" },
  ],
  CL: [
    { name: "Banco BCI", code: "BCI" },
    { name: "Banco de Chile", code: "BCH" },
    { name: "Banco Estado", code: "EST" },
    { name: "Banco Falabella", code: "FAL" },
    { name: "Santander Chile", code: "SAN" },
  ],
  PE: [
    { name: "Banco de Crédito (BCP)", code: "BCP" },
    { name: "BBVA Peru", code: "BBVA" },
    { name: "Interbank", code: "INT" },
    { name: "Scotiabank Peru", code: "SCO" },
  ],
  IE: [
    { name: "AIB (Allied Irish Banks)", code: "AIB" },
    { name: "Bank of Ireland", code: "BOI" },
    { name: "KBC Ireland", code: "KBC" },
    { name: "Permanent TSB", code: "PTB" },
  ],
  NZ: [
    { name: "ANZ New Zealand", code: "ANZ", routingNumber: "010" },
    { name: "ASB Bank", code: "ASB", routingNumber: "012" },
    { name: "BNZ (Bank of New Zealand)", code: "BNZ", routingNumber: "020" },
    { name: "Kiwibank", code: "KWI", routingNumber: "389" },
    { name: "Westpac NZ", code: "WPC", routingNumber: "030" },
  ],
  LK: [
    { name: "Bank of Ceylon", code: "BOC" },
    { name: "Commercial Bank of Ceylon", code: "CBC" },
    { name: "Hatton National Bank", code: "HNB" },
    { name: "Sampath Bank", code: "SAM" },
  ],
  PT: [
    { name: "Caixa Geral de Depósitos", code: "CGD" },
    { name: "Millennium bcp", code: "MCP" },
    { name: "Novobanco", code: "NVB" },
    { name: "Santander Portugal", code: "SAN" },
  ],
  GR: [
    { name: "Alpha Bank", code: "ALB" },
    { name: "Eurobank", code: "EUR" },
    { name: "National Bank of Greece", code: "NBG" },
    { name: "Piraeus Bank", code: "PIR" },
  ],
  AT: [
    { name: "Bank Austria", code: "BA" },
    { name: "Erste Bank", code: "ERS" },
    { name: "Raiffeisen Bank Austria", code: "RAI" },
  ],
  BE: [
    { name: "Argenta", code: "ARG" },
    { name: "BNP Paribas Fortis", code: "BNP" },
    { name: "Belfius", code: "BEL" },
    { name: "ING Belgium", code: "ING" },
    { name: "KBC Belgium", code: "KBC" },
  ],
  DK: [
    { name: "Arbejdernes Landsbank", code: "ALB" },
    { name: "Danske Bank", code: "DAN" },
    { name: "Jyske Bank", code: "JYS" },
    { name: "Nordea Denmark", code: "NOR" },
    { name: "Sydbank", code: "SYD" },
  ],
  FI: [
    { name: "Nordea Finland", code: "NOR" },
    { name: "OP Financial Group", code: "OPF" },
    { name: "S-Bank", code: "SBK" },
  ],
  HU: [
    { name: "K&H Bank", code: "KH" },
    { name: "MBH Bank", code: "MBH" },
    { name: "OTP Bank", code: "OTP" },
    { name: "Raiffeisen Hungary", code: "RAI" },
  ],
  CZ: [
    { name: "Česká spořitelna", code: "CS" },
    { name: "Komerční banka", code: "KB" },
    { name: "MONETA Money Bank", code: "MON" },
    { name: "Raiffeisen CZ", code: "RAI" },
  ],
  RO: [
    { name: "Banca Transilvania", code: "BT" },
    { name: "BCR", code: "BCR" },
    { name: "BRD", code: "BRD" },
    { name: "ING Romania", code: "ING" },
  ],
  // Oceania
  FJ: [
    { name: "ANZ Fiji", code: "ANZ" },
    { name: "Bank South Pacific", code: "BSP" },
    { name: "HFC Bank Fiji", code: "HFC" },
    { name: "Westpac Fiji", code: "WPC" },
  ],
  PG: [
    { name: "ANZ Papua New Guinea", code: "ANZ" },
    { name: "Bank South Pacific", code: "BSP" },
    { name: "Kina Bank", code: "KIN" },
    { name: "Westpac PNG", code: "WPC" },
  ],
  WS: [
    { name: "ANZ Samoa", code: "ANZ" },
    { name: "Bank South Pacific Samoa", code: "BSP" },
    { name: "National Bank of Samoa", code: "NBS" },
  ],
};

/** Returns banks for a given ISO country code, or an empty array if not found */
export function getBanksForCountry(countryCode: string): Bank[] {
  return BANKS_BY_COUNTRY[countryCode.toUpperCase()] ?? [];
}
